language: node_js

node_js:
  - 9
  - node

cache: npm

script:
  - npm run lint
  - npm run test:ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    # If this is a tagged commit, publish the package to npm
    - stage: npm release
      if: tag IS present
      deploy:
        - provider: npm
          skip_cleanup: true
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          tag: latest
          on:
            branch: master
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
        - provider: npm
          skip_cleanup: true
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          tag: next
          on:
            branch: master
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|next)\.[0-9]+$
